### PR TITLE
drop python 3.2

### PR DESCRIPTION
**Pull request by valera-rozuvan**
Python 3.2 is not supported by some of the modules used in this project. So the build fails for that specific version. It was discussed in https://github.com/tadeck/onetimepass/pull/22 , and agreed that dropping 3.2 is the best option.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
You should also remove the classifier for it: https://github.com/tadeck/onetimepass/blob/858cb14/setup.py#L35

**Comment by valera-rozuvan** [comment]
@WhyNotHugo Done! PR is updated.

**Comment by valera-rozuvan** [comment]
@tadeck Any questions/comments on this PR? Can we get it merged please?

**Comment by valera-rozuvan** [comment]
@tadeck - are you around to merge this PR? Let's get this project moving again :-)

**Comment by valera-rozuvan** [comment]
Closing this due to inactivity from maintainer.

**Pull request closed without merging**
